version: "3"

tasks:

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod tinygo run -target=gameboy-advance main.go

    build:
        desc: Build the GBA app
        cmds:
        - GOFLAGS=-mod=mod tinygo build -size short -o bin/main.gba -target=gameboy-advance main.go

    build-mgba:
        desc: Build the GBA app for mGBA
        cmds:
        - GOFLAGS=-mod=mod tinygo build -size short -o bin/main.elf -target=gameboy-advance main.go
        - mv bin/main.elf bin/main.gba

    mgba:
        desc: Load the game
        cmds:
        - mgba bin/main.gba